### ISSUE TITLE
点击展示分时图，K线没有展示出来

### ISSUE THREAD

**Issue by hezhipengzipp** [scsfwgy/FinancialCustomerView#25]

**Comment by scsfwgy** [comment]
请详细描述

**Comment by kejunlu** [comment]
K线图竖屏界面，点击展示蜡烛图，主图没有显示蜡烛图，必须手势点击下主图才会显示蜡烛图

**Comment by scsfwgy** [comment]
fix:#25,仍然有一点小问题，具体可以查看{@link KLayoutView#setShowMinor(boolean showMinor)}
