### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by rtyheji** [scsfwgy/FinancialCustomerView#28]
在蜡烛图的时候加载更多 比如boll线这些会乱掉

**Comment by scsfwgy** [comment]
fix:#28。这个问题其实在分时图中也存在。另外，注意看加载更多成功后主图和副图不应该变化的。但是副图（macd）有变化，这个不是bug,和macd的算法有关（macd起始几个点的计算取值有关）。

**Comment by scsfwgy** [comment]
![image](https://user-images.githubusercontent.com/16045179/40267483-8ac32b02-5b8f-11e8-87c2-c777c5a9fa97.png)
起始点的计算取收盘价，导致加载历史数据后所有之前的madc都会发生一点变化。
