### ISSUE TITLE
长按显示问题

### ISSUE THREAD

**Issue by kejunlu** [scsfwgy/FinancialCustomerView#30]
长按顶部显示信息时，有时会一直存在，再次点击下也不会消失

**Comment by scsfwgy** [comment]
长按后顶部的信息会显示出来，再次点击会消失（不点击不会消失）。不会消失，是否能重现？

**Comment by kejunlu** [comment]
我用Genymotion 模拟器测试出现上述情况，估计是模拟器问题，真机测试正常。
建议：一般长长按显示交易信息，手势离开屏幕一定时间后顶部消息应该自动消失

**Comment by scsfwgy** [comment]
好的，这个后期我会加一个flag,控制是否自动消失

**Comment by xybCoder** [comment]
长按十字线不消失
